# Generated by Django 5.0.7 on 2024-08-08 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='club_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='chess.club'),
        ),
    ]
